env:
  # Cirrus Specific Vars (Do *NOT* Change)
  CIRRUS_SHELL: bash

task:
  name: "Decrypt OFP"
  timeout_in: 120m
  container:
    # image: ghcr.io/sushrut1101/docker:arch
    image: ubuntu:latest
    cpu: 8
    memory: 20G

  setup_script:
    - apt-get -y update
    - apt-get -y upgrade
    - apt-get -y install python3 python3-pip curl wget git aria2 7zip
    - git clone https://github.com/bkerler/oppo_decrypt
    - aria2c https://www.7-zip.org/a/7z2201-linux-x64.tar.xz
    - tar -xf *.xz
    - rm -f *.xz

  download_script:
    - aria2c -x16 -s16 $(cat link.txt)

  unarchive_script:
    - ./7zz x *.7z *.zip

  decrypt_script:
    - bash decrypt.sh

